kind_wildcat.content_chunk_type.*:
  type: config_entity
  label: 'Content chunk type config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    uuid:
      type: string
